name: mcserv
description: CLI util to generate and download mc server files.
## !!!!!!!!!
## DO NOT CHANGE THIS VERSION!
## Change the version in the build.gradle.kts instead
version: 1.0.0
homepage: https://mcserv.how

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  interact: ^2.1.1
  meta: ^1.7.0
  file: ^6.1.2
  logging: ^1.0.1
  retrofit: ^2.0.1
  json_annotation: ^4.1.0
  crypto: ^3.0.1
  http: ^0.13.3
  ffi: ^1.1.2
  path: ^1.8.0
  args: ^2.2.0
  equatable: ^2.0.3
  archive: ^3.1.2
  intl: ^0.17.0
  pub_semver: ^2.0.0
  filesize: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.1
  retrofit_generator: ^2.0.1
  json_serializable: ^5.0.0
  intl_translation:
    git:
      ref: master
      url: https://github.com/DRSchlaubi/intl_translation.git
